/**
 * Turns src/content/posts/*.md into src/generated/posts.ts.
 *
 * Runs before every build (see the `content` script in package.json). The site is
 * served as static assets on Cloudflare with no Worker entry, so there is no runtime
 * to parse markdown on — every post has to be baked into the bundle and prerendered.
 */
import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { marked } from 'marked';

const POSTS_DIR = join('src', 'content', 'posts');
const OUT_DIR = join('src', 'generated');
const OUT_FILE = join(OUT_DIR, 'posts.ts');

const MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
const WORDS_PER_MINUTE = 200;

/** Splits a leading `---` fenced block off the top of the file. */
function splitFrontmatter(raw, file) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw.trimStart());
  if (!match) {
    throw new Error(`${file}: missing the --- frontmatter block at the top of the file`);
  }

  const data = {};
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const sep = line.indexOf(':');
    if (sep === -1) {
      throw new Error(`${file}: frontmatter line is not "key: value" — ${line}`);
    }
    const key = line.slice(0, sep).trim();
    const value = line
      .slice(sep + 1)
      .trim()
      .replace(/^["'](.*)["']$/, '$1');
    data[key] = value;
  }

  return { data, body: match[2] };
}

/** "2026-07-30" -> "30 JUL 2026". Built by hand so the output never shifts with locale. */
function formatDate(iso, file) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (!match) {
    throw new Error(`${file}: date must be YYYY-MM-DD, got "${iso}"`);
  }
  const [, year, month, day] = match;
  const monthName = MONTHS[Number(month) - 1];
  if (!monthName) {
    throw new Error(`${file}: "${iso}" is not a real month`);
  }
  return `${day} ${monthName} ${year}`;
}

function readingMinutes(body) {
  const words = body
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!?\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/[#>*_`~\-]/g, ' ')
    .split(/\s+/)
    .filter(Boolean).length;
  return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** Headings get ids so posts can be deep-linked; images lazy-load and stay in their column. */
function createRenderer() {
  const renderer = new marked.Renderer();

  renderer.heading = ({ tokens, depth }) => {
    const text = renderer.parser.parseInline(tokens);
    const id = slugify(text.replace(/<[^>]*>/g, ''));
    return `<h${depth} id="${id}">${text}</h${depth}>\n`;
  };

  renderer.image = ({ href, title, text }) => {
    const titleAttr = title ? ` title="${title}"` : '';
    return `<img src="${href}" alt="${text}"${titleAttr} loading="lazy" decoding="async">`;
  };

  return renderer;
}

async function main() {
  let files = [];
  try {
    files = (await readdir(POSTS_DIR)).filter((f) => f.endsWith('.md')).sort();
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
    console.log(`content: no ${POSTS_DIR} directory yet — writing an empty post list`);
  }

  const renderer = createRenderer();
  const posts = [];

  for (const file of files) {
    const raw = await readFile(join(POSTS_DIR, file), 'utf8');
    const { data, body } = splitFrontmatter(raw, file);

    for (const required of ['title', 'date', 'summary']) {
      if (!data[required]) {
        throw new Error(`${file}: frontmatter is missing "${required}"`);
      }
    }

    posts.push({
      slug: basename(file, '.md'),
      title: data.title,
      date: data.date,
      dateLabel: formatDate(data.date, file),
      summary: data.summary,
      cover: data.cover ?? null,
      readingMinutes: readingMinutes(body),
      html: marked.parse(body, { gfm: true, renderer, async: false }),
    });
  }

  // Newest first — the landing page reads top-down as most recent to oldest.
  posts.sort((a, b) => b.date.localeCompare(a.date));

  const duplicates = posts.map((p) => p.slug).filter((slug, i, all) => all.indexOf(slug) !== i);
  if (duplicates.length) {
    throw new Error(`two posts share the slug "${duplicates[0]}" — filenames must be unique`);
  }

  const out = `// Generated by scripts/build-content.mjs. Do not edit — your changes will be
// overwritten on the next build. Edit the markdown in src/content/posts/ instead.

export interface Post {
  slug: string;
  title: string;
  /** ISO date, for the datetime attribute. */
  date: string;
  /** Display date, e.g. "30 JUL 2026". */
  dateLabel: string;
  summary: string;
  cover: string | null;
  readingMinutes: number;
  /** Rendered markdown. Authored by us at build time, never user input. */
  html: string;
}

export const posts: Post[] = ${JSON.stringify(posts, null, 2)};
`;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FILE, out, 'utf8');
  console.log(`content: ${posts.length} post${posts.length === 1 ? '' : 's'} -> ${OUT_FILE}`);
}

main().catch((error) => {
  console.error(`content: ${error.message}`);
  process.exit(1);
});
